version: '3'
volumes:
  patas_e_pelos-db-data:
    driver: local
services:
  hyperf-skeleton:
    container_name: patas_e_pelos
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    entrypoint: sh ./hyper.sh
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
  db:
    image: mysql:latest
    container_name: patas_e_pelos-db
    volumes:
      - patas_e_pelos-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patas_e_pelos
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"

networks:
  default:
    name: hyperf-skeleton